### PR TITLE
Fix `page_size` parameter in AssetsResource and ReleaseListResource

### LINKED ISSUE #184: ongoing issue with website/v3api not showing latest openj9 releases
Seem this problem persists, the jdk-11.0.7+10_openj9-0.20.0 MacOSXL build that was publish last night, was still not visible midday today.... George had to manually update the API...
I think we need to get to the bottom of this issue?
Is it anything to do with github rate limiting?

### PR DESCRIPTION
**Pull request by joschi**
The `page_size` query parameter was incorrectly handled in `AssetsResource` and capped to an undocumented limit of 20 items per page.

In `ReleaseListResource`, the `page_size` query parameter wasn't used at all, although documented in the API specification (via Swagger).

Fixes #184

# Checklist

- [x] You added tests to cover the change
- [x] `mvn clean install` build and test completes

### CODE REVIEW

File: adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package net.adoptopenjdk.api.v3
+
+import kotlin.math.min
+
+object Pagination {
+    private const val defaultPageSizeNum = 10
+    private const val maxPageSizeNum = 500
```
Comment (johnoliver) [inline adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt:7]: Max size of 500 may be excessive, I estimate that would set up a 4.5Mb download, I think 50 may be more reasonable

File: adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    fun <T> getPage(pageSize: Int?, page: Int?, releases: Sequence<T>): List<T>? {
+        val pageSizeNum = min(maxPageSizeNum, (pageSize ?: defaultPageSizeNum))
+        val pageNum = page ?: 0
+
+        val chunked = releases.chunked(pageSizeNum)
+
+        return try {
+            chunked.elementAt(pageNum)
+        } catch (e: IndexOutOfBoundsException) {
+            null
```
Comment (johnoliver) [inline adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt:20]: I think it may be better to throw the exception here rather than return null then throw

**Comment by johnoliver** [comment]
A few small fixes but looks good, thanks for the help. Unfortunately not getting a clean test due to an unrelated issue

File: adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt (hunk 1 above)
Comment (johnoliver) [reply adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt:7]: In fact given the current max is 20, can go with 20 to maintain consistency

Comment (joschi) [reply adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt:7]: @johnoliver Is this really a problem? The default would still be 10 items per page and unless people override the page size, this wouldn't change the current behavior.

I would go with a maximum of 100 items per page, if that's okay. Otherwise we wouldn't have to merge this PR at all.
Its purpose is, after all, to enable page sizes larger than 20 items. 😉

Comment (johnoliver) [reply adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt]: I viewed the main benefit of this PR about adding the page limit to the Release List resource and documenting the maximum, not to increase the maximum. Although it was incorrectly not documented that there was a limit of 20, it was intended for 20 to be the maximum. I am not sure if there is a usecase I want to support that would allow people to access 100 releases with a single request. In the case of the release_names given it is just returning strings I agree that a higher limit is fine, so if you want to have 100 or even 500 on that endpoint, fine, but for the other endpoint 100 releases is still a lot for a single request.

File: adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt (hunk 2 above)
Comment (joschi) [reply adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt]: ✅

File: adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt (hunk 1 above)
Comment (joschi) [reply adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt]: @johnoliver Just so I understand the restrictions properly:
Is it about the size of the HTTP response and the resources the application requires to serialize the payload, to reduce the load on the database, or to prevent "sloppy" (misbehaving) clients from fetching too many items at once?

I can speak for my use case, which is always fetching the complete release list and avoid making more HTTP request roundtrips than necessary in https://github.com/joschi/java-metadata/blob/master/bin/adoptopenjdk.bash#L119-L127.

**Comment by karianna** [comment]
@joschi 

`/home/runner/work/openjdk-api-v3/openjdk-api-v3/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt:22:1: Unused import`

**Comment by karianna** [comment]
TEst fail:

```
[mongod output] 
[INFO] Tests run: 131, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 102.777 s - in net.adoptopenjdk.api.AssetsResourceFeatureReleasePathTest
2020-05-24 14:28:35,002 INFO  [io.quarkus] (main) Quarkus stopped in 0.070s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ReleaseNamesPathTest.releaseNames:16 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ReleaseNamesPathTest.releaseNamesPageSize:26 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ReleaseNamesPathTest.releaseNamesSortOrder:36 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ReleaseNamesPathTest.releaseVersions:46 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ReleaseNamesPathTest.releaseVersionsPageSize:56 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   ReleaseNamesPathTest.releaseVersionsSortOrder:66 1 expectation failed.
Expected status code <200> but was <404>.
```

**Comment by joschi** [comment]
It looks like the repository for releases (`APIDataStore.getAdoptRepos().getReleases(releaseFilter, sortOrder)`) isn't properly populated in the tests.

Previously, the `/v3/info/release_names` and `/v3/info/release_versions` resources returned an empty response with HTTP status 200, but now they return a response with HTTP status 404.

Should I restore the previous behavior or try fixing the underlying issue with the tests?

**Comment by joschi** [comment]
@johnoliver How should we move on with this PR?

**Comment by johnoliver** [comment]
@joschi my only outstanding issue is the 100 limit on releases, 100+ on the release names is fine, but being able to generate 2mb responses is quite a lot for an api. 

With your usecase of fetching the entire dataset with few round trips, currently for 8 I believe we only have somewhere around 28 ga releases and that is for everything i.e hotspot+openj9+upstream binaries, so would only require 1 extra request right now with a 20 limit. For EAs I would question the need to offer more than a limited range and there has been discussion of removing a number of older nightly releases as they may not be serving any purpose.

I get that only having 28 ga releases could also be an argument for "well if there are only 28 what does it matter if its 20 or 100". My worry would be that once we raise the limit we cannot go smaller without it being an api breaking change which is painful.

**Comment by joschi** [comment]
@johnoliver I've updated the PR and set the maximum page size to 20 items.

> With your usecase of fetching the entire dataset with few round trips, currently for 8 I believe we only have somewhere around 28 ga releases and that is for everything i.e hotspot+openj9+upstream binaries, so would only require 1 extra request right now with a 20 limit.

This has been updated, too. 😉 
https://github.com/joschi/java-metadata/blob/ef52081c1bd0433861acdcf3fec9213841408ce6/bin/adoptopenjdk.bash#L124-L131

**Comment by johnoliver** [comment]
Awesome thanks
