### PR TITLE
Explicitly set serverSelectionTimeoutMS for 'fallback' Mongo connection string

### LINKED ISSUE #238: Test suite currently takes ~40 mins to run
@johnoliver and I were discussing this yesterday and having started working with codebase it feels like it would be good to resolve the issue to improve the development feedback loop.

At present when each test class is executed there is an initial hit of between 1 and 2 minutes depending on the test. This acunulates to an overall time of ~40 mins to run the front-end test suite.

This is because the tests use the @QuarkusTest annotation which initialises the full app including the code that creates connections to Mongo. The default connect timeout for Mongo is 30000 milliseconds so every time a connection is attempted we get this hit.

We see these errors in the logs:

```
ERROR: Failed to read db
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]
	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:403)
	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:311)
	at com.mongodb.internal.connection.BaseCluster.access$800(BaseCluster.java:62)
	at com.mongodb.internal.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:474)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

As a simple test for a fix I've modified the fallback localhost connection string that's used by the tests [here](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt#L45) to this:

```
"mongodb://$host:$port?connectTimeoutMS=100"
```

The full test suite now runs in ~8 mins with the front-end tests reduced to ~5/6 mins:

```
[INFO] Reactor Summary for adoptopenjdk-api-v3 3.0.0-SNAPSHOT:
[INFO] 
[INFO] adoptopenjdk-api-v3 ................................ SUCCESS [  2.351 s]
[INFO] adoptopenjdk-api-v3-models ......................... SUCCESS [ 11.861 s]
[INFO] adoptopenjdk-api-v3-persistance .................... SUCCESS [  2.875 s]
[INFO] adoptopenjdk-api-v3-updater ........................ SUCCESS [02:41 min]
[INFO] adoptopenjdk-api-v3-frontend ....................... SUCCESS [05:29 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:28 min
[INFO] Finished at: 2020-07-16T08:30:57+01:00
[INFO] ------------------------------------------------------------------------
```

We could probably reduce this more but that's as far as I've gone for now, thought it was worth getting some feedback first.

I think as a quick win this could be a good change to improve the speed of the test run improving the feedback loop. 

Please let me know if you're happy for me to create a PR for this?

As the tests are using an in memory database controlled by the tests, longer term it may be worth thinking about how we either change the Mongo connection code to occur later in the application life-cycle so the database is already available. Or alternatively, and maybe preferably, change how we use Mongo in the tests so it's available before the Mongo client is created. Maybe something like test containers could help here, or even using docker-compose to wrap the test execution and spin up Mongo as a dependency.

---
Additional note: 

It's possible we'd want to apply a more aggressive timeout more generally than just the tests but that decision probably requires a bit more thought. In production waiting 30000ms for Mongo to notify that connection has failed might be too long, if we can fail faster then that might be a good thing. (I don't have much context yet on how this runs in prod).

### PR DESCRIPTION
**Pull request by nickebbitt**
When the tests are executed a number of attempts are made to initialise the
MongoClient before the Mongo instance has been initialised. By default, this
triggers a 30000ms timeout for each attempt.

The 'fallback' Mongo connection string is only used when the
Mongo user & password environment variables are not passed and therefore
only applies for local development/testing use-cases.

This change shortens the timeout to 100ms reducing overall test suite execution
time from ~40 mins to ~8 mins.

Fixes #238

# Checklist

- [x] `mvn clean install` build and test completes

### CODE REVIEW

File: adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt [hunk 1]
```diff
@@ -42,7 +42,7 @@ class MongoClient {
         var uri = if (username != null && password != null) {
             "mongodb://$username:$password@$host:$port/$dbName"
         } else {
-            "mongodb://$host:$port"
+            "mongodb://$host:$port/?serverSelectionTimeoutMS=100"
```
Comment (karianna) [inline adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt:45]: If you extract that number to a named const it can also double down as documentation as to why you chose that number. LOCAL_LOOPBACK_TIMEOUT_FOR_DEVELOPMENT or something like that

Bonus points if this number is extracted to a properties file

Comment (nickebbitt) [reply adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt:45]: will do - was unsure how far to go for the change but agree with your suggestions so will work them through

Comment (johnoliver) [reply adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt:45]: I think I would also put it into a property that defaults to 60000, and then overridden to 100 in tests, I think 100 should be ok in prod but not sure

Comment (nickebbitt) [reply adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt:45]: This might be where I'm missing some context on how the API runs in prod as the code path for this connection string feels like one that would only ever be exercised either by tests or by running the app locally and not specifying the `MONGODB_USER` and `MONGODB_PASSWORD`. 

I think the tests don't actually use this string, at least the ones that extend `BaseTest`, as they define the `MONGO_DB` system property which is used instead.

Comment (johnoliver) [reply adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt:45]: that is true, ok fair enough

Comment (nickebbitt) [reply adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt:45]: oh merged :) I'll still action Martijn's comments to improve the intent of that connection string and put that up as a new PR
